export { default as Login } from "./Login/Login"
export { default as Home } from "./Home/Home"
export { default as SignUp } from "./SignUp/SignUp"
export { default as SplashScreen } from "./SplashScreen"
export { default as TestingPage } from "./TestingPage"