export { default as Login } from "./Login/Login"
export { default as Home } from "./Home/Home"
export { default as SignUp } from "./SignUp/SignUp"
export { default as SplashScreen } from "./SplashScreen"
export { default as TestingPage } from "./TestingPage"
export { default as SeriesPage } from "./Series/series"
export { default as PokemonPage } from "./Pokemon/Pokemon"